config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews
    mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :book
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    # call this method before calling any action on this page
    before_action :find_book, only: [:edit, :update, :show, :destory]
    before_action :authenticate_user!, only: [:new, :edit]
    def index
        if params[:category].blank?
            @books = Book.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @books = Book.where(:category_id => @category_id).order("created_at DESC")
        end
    end

    def new
        @book = current_user.books.build
        @categories = Category.all.map{ |c| [c.name, c.id]}
    end
    
    def show 
        if @book.reviews.blank?
            @average_review = 0
        else
            @average_review = @book.reviews.average(:rating).round(2)
        end
    end

    def create
      @book = current_user.books.build(book_params)
      @book.category_id = params[:category_id]
      if @book.save
        redirect_to root_path
      else
        render 'new'
      end
    end

    def edit 
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update
        @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to root_path
    end

    private

        def book_params
            params.require(:book).permit(:title, :description, :author, :category_id, :image)
        end 

        def find_book
            @book = Book.find(params[:id])    
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destory]
    before_action :authenticate_user!, only: [:new, :edit]
    def new
        @review = Review.new 
    end

    def create
        @review = Review.new(review_params)
        @review.book_id = @book.id
        @review.user_id = current_user.id
        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end

    def edit 
    end

    def update
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to book_path(@book)
    end
    private
        def review_params
            params.require(:review).permit(:rating, :comment)
        end

        def find_book
            @book = Book.find(params[:book_id])
        end

        def find_review
            @review = Review.find(params[:id])   
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => {:multipart => true } do |f|%>
    <%= select_tag :category_id, options_for_select(@categories), :prompt => "select an category" %>
    <%= f.file_field :image %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description %>
    <%= f.input :author, label: "Author" %>
    <% if @book.title.to_s.strip.empty? == false %>    
        <button type="submit" class="btn btn-outline-success">Update Book</button>
    <% else %>
        <%= f.button :submit, :class => 'btn-custom2'%>
        <!--<button type="submit" class="btn btn-outline-success">Create Book</button> -->
    <% end %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-10">
    <div class="edit-book-form">
        <h2>Edit the Book</h2>
        <%= simple_form_for @book, :html => {:multipart => true } do |f|%>
            <%= f.select :category_id, @categories %>
            <%= f.file_field :image %>
            <%= f.input :title, label: "Book Title" %>
            <%= f.input :description %>
            <%= f.input :author, label: "Author" %>
            <%= f.button :submit, :class => 'btn-custom2'%>
        <% end %>
    </div>
</div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
    <h1>There are no books currently in this category!</h1>
<% else %>
    <div class="row">
        <% @books.each do |book| %>
        <div class="col-md-4">
            <a href="/books/<%= book.id %>">
                <!--<%= image_tag  book.image.url%>-->
                <img src="<%= book.image.url %>" class="book">
            </a>
        </div>
        <% end %>
    </div>
<% end %>

app/views/books/new.html.erb
<div class="col-md-10">
    <div class="new-book-form">
        <h1>New Book</h1>
        <%= render  "form" %>
    </div>
</div>

app/views/books/show.html.erb
<div class="row">
    <div class="col-md-4">
        <!-- showing the image -->
        <img src="<%= @book.image.url %>" class="book-show">
    </div>
    <!-- showing the book content -->
     <div class="col-md-8">
        <div class="book-info">
            <h2 class="book-title"> <%= @book.title%></h2>
            <h3 class="book-author"><%= @book.author%></h3>
            <h2 class="avg-rating">Average Rating</h2>
            <div class="average-review-rating" data-score=<%= @average_review %> > </div>
            <span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews </span>  
            <p class="book-desc"> <%= @book.description%></p>
        </div>
    </div>
</div>

<!-- reviews section started-->
<div class="row">
    <div class="col-md-4">
        <div class="reviews">
            <h1>Reviews</h1>
            <%= render @book.reviews %>
            <div>
                <%= link_to  "Add review", new_book_review_path(@book),class:"btn btn-custom" %>
            </div>
        </div>
    </div>
</div>
<div class="link btn-group">
    <!-- links for the book -->
    <%= link_to  "Back", root_path, class:"btn btn-custom" %>
    <% if user_signed_in? %>
        <% if @book.user_id == current_user.id %>
            <%= link_to  "Edit", edit_book_path(@book),class:"btn btn-custom" %>
            <%= link_to  "Delete", book_path(@book), method: :delete, data:{confirm:"Are you sure to delete this book?"},class:"btn btn-custom" %>
        <% end %>
    <% end %>
</div>


<!-- raty.js magic -->
<script>
    $('.review-rating').raty({
        readOnly: true,
        score: function(){
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

<script>
    $('.average-review-rating').raty({
        readOnly: true,
        path: '/assets/',
        score: function(){
            return $(this).attr('data-score');
        }
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <%= stylesheet_link_tag "BOOTSTRAP_FOUR", media: 'all'%>
    <%= stylesheet_link_tag "final", media: 'all'%> 
    <%= javascript_include_tag 'JSONE'%>
    <%= javascript_include_tag 'JSTWO'%>
    <%= javascript_include_tag 'JSTHREE'%>
    <%= javascript_include_tag 'jquery.raty'%>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Book Review", root_path, class:"navbar-brand" %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li>
                <%= link_to  "Sign Up", new_user_registration_path, class:"nav-link"%>
              </li>
             <% if user_signed_in? %>
                <li>
                  <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
                </li>
              <% else %>
                <li>
                  <%= link_to  "Log In", new_user_session_path, class:"nav-link" %>
                </li>
             <% end %>
          </ul>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown" role="menu">
              <% cnt = 0 %>
                <% Category.all.each do |category| %>
                  <% count = Category.count %>
                  <li class="<%= 'active' if params[:category] == category.name %>"><%= link_to  category.name, books_path(category: category.name), class:"dropdown-item" %> </li>
                  <% cnt = cnt + 1 %>
                  <% if cnt < count %>
                    <div class="dropdown-divider"></div>
                  <% end %>
                <% end %>
              </ul>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to  "Add Book", new_book_path, class:"nav-link"%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@book, @book.reviews.build]) do |f|%>
    <div id="rating-form">
        <label>Rating :</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit, :class => "btn-custom2"%>
<% end %>
<!-- dyanamic stars rating system -->
<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    });
</script>

app/views/reviews/_review.html.erb
<div class="review">
    <div class="review-rating" data-score="<%= review.rating %>"></div>
    <p class="review-comment"> <%= review.comment %> </p>

    <% if user_signed_in? %>
        <% if review.user_id == current_user.id %>
            <div class="links btn-group">
                <%= link_to  "Edit", edit_book_review_path(review.book, review),class:"btn btn-custom" %>
                <%= link_to  "Delete", book_review_path(review.book, review), method: :delete, date: {confirm: "Are you sure?"},class:"btn btn-custom" %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10">
    <div class="edit-review-form">
        <h1>Edit Review</h1>
        <%= simple_form_for ([@book, @review]) do |f| %>
            <div id="rating-form">
                <label>Rating :</label>
            </div>
            <%= f.input :comment %>
            <%= f.button :submit, :class => "btn-custom2" %>
        <% end %>
        <script>
            $('#rating-form').raty({
                path: '/assets/',
                scoreName: 'review[rating]'
            });
        </script>
    </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-10">
    <div class="new-review-form">
        <h1>New Review</h1>
        <%= render 'form' %>
    </div>
</div>